workflows:
  ios-testflight:
    name: Alison TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Alison
    environment:
      ios_signing:
        provisioning_profiles:
          - alison
        certificates:
          - Alison1
      vars:
        BUNDLE_ID: "al.alison.app"
        APP_STORE_APPLE_ID: 6804735818
        XCODE_PROJECT: "Alison/Alison.xcodeproj"
        XCODE_SCHEME: "Alison"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd "$CM_BUILD_DIR/Alison"
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID" || echo 0)
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
